### ISSUE TITLE
AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'leaky_relu' swig/python detected a memory leak of type 'int64_t *', no destructor found.

### ISSUE THREAD

**Issue by EMCL** [kaka-lin/object-detection#1]
Traceback (most recent call last):
  File "test_tiny_yolo.py", line 104, in <module>
    yolo_model = load_model("model_data/tiny-yolo.h5")
  File "C:\Users\Admin\Anaconda3\envs\tfdeeplearning\lib\site-packages\keras\models.py", line 243, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "C:\Users\Admin\Anaconda3\envs\tfdeeplearning\lib\site-packages\keras\models.py", line 317, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "C:\Users\Admin\Anaconda3\envs\tfdeeplearning\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "C:\Users\Admin\Anaconda3\envs\tfdeeplearning\lib\site-packages\keras\utils\generic_utils.py", line 144, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\Users\Admin\Anaconda3\envs\tfdeeplearning\lib\site-packages\keras\engine\topology.py", line 2524, in from_config
    process_node(layer, node_data)
  File "C:\Users\Admin\Anaconda3\envs\tfdeeplearning\lib\site-packages\keras\engine\topology.py", line 2481, in process_node
    layer(input_tensors[0], **kwargs)
  File "C:\Users\Admin\Anaconda3\envs\tfdeeplearning\lib\site-packages\keras\engine\topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Users\Admin\Anaconda3\envs\tfdeeplearning\lib\site-packages\keras\layers\advanced_activations.py", line 46, in call
    return K.relu(inputs, alpha=self.alpha)
  File "C:\Users\Admin\Anaconda3\envs\tfdeeplearning\lib\site-packages\keras\backend\tensorflow_backend.py", line 2921, in relu
    x = tf.nn.leaky_relu(x, alpha)
AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'leaky_relu'
swig/python detected a memory leak of type 'int64_t *', no destructor found.

**Comment by mattwang44** [comment]
@EMCL What's your platform, python version, & tf version?

**Comment by EMCL** [comment]
python 3.5 and tensorflow 1.0

**Comment by mattwang44** [comment]
@EMCL Please upgrade your tf first then try again. Many functions have been moved to different places after ver1.0 and leaky_relu is one of them.

`activate conda-env-name`
`pip install pip --upgrade`
`pip install tensorflow --upgrade`

The commands above should upgrade your tf to version 1.7.0

**Comment by EMCL** [comment]
i have upgraded to latest...now it gives this error
C:\Users\Admin\Anaconda3\envs\tfdeeplearning\lib\site-packages\keras\models.py:252: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '

**Comment by kaka-lin** [comment]
@EMCL 
https://github.com/keras-team/keras/issues/6865

**Comment by mattwang44** [comment]
@EMCL 
Please change the line
`load_model("model_name.h5")`
to
`load_model("model_name.h5", compile=False)`

**Comment by EMCL** [comment]
modified to `yolo_model = load_model("model_data/tiny-yolo.h5",compile=False)`
then its give like this
`\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2`

**Comment by mattwang44** [comment]
@EMCL 
It just a warning(please see [this](https://stackoverflow.com/questions/47068709/your-cpu-supports-instructions-that-this-tensorflow-binary-was-not-compiled-to-u)), the code should have executed properly. Try to feed in different pictures and check if it works well.

**Comment by kaka-lin** [comment]
@EMCL 
you can simply ignore this warning by

```python
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'
import tensorflow as tf
```
